name: Build and test Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Build
        env:
            GOPROXY: "off"
        run: make binraries

      - name: Test
        env:
            GOPROXY: "off"
        run: make test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build Docker Image
        run: make docker/image